name: Conditional Context

on: [push, pull_request]

jobs:
    conditional-execution:
        runs-on: ubuntu-latest
        steps:
            - name: Check if pull request from main
              if: ${{ github.event_name == 'pull_request' && github.event.action == 'opened' && github.event == 'refs/heads/dev' }}
              run: echo Detected a pull request from the main branch

            - name: Running deployment
              if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
              run: echo Running deployment for the main branch