on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  greetings:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      id: first-interaction
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Message that will be displayed on users' first issue"
        pr-message: "Message that will be displayed on users' first pull request"
    - name: Greetings result
      run: |
        echo "Greetings result: ${{ steps.first-interaction.outputs.result }}"