name: Publish Docker App

on: [workflow_dispatch]

permissions:
    packages: write

defaults:
    run:
        working-directory: docker-app

jobs:
    BuildAndPublish:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            
            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.repository_owner }}
                password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build Docker image
              run: docker build -t ghcr.io/${{ github.repository_owner}}/github-actions-training:latest  .

            - name: Push Docker image
              run: docker push ghcr.io/${{ github.repository_owner}}/github-actions-training:latest
            