name: Publish Docker App

on: [workflow_dispatch]

permissions:
    packages: write

defaults:
    run:
        working-directory: docker-app

jobs:
    BuildAndPublish:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            
            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.repository_owner }}
                password: ${{ secrets.GITHUB_TOKEN }}

            - name: Setup Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build and Push
              uses: docker/build-push-action@v6
              with:
                push: true
                tags: ${{ github.repository_owner}}/githubactionstraining:latest